name: Update README Timestamp

on:
  schedule:
    - cron: '0 0 2-31/2 * *' # At midnight on every 2nd, 4th, 6th... day of the month
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate multiple random timestamps
        run: |
          for i in {1..8}; do
            echo "TIMESTAMP$i=$(( $(date +%s) + $RANDOM ))" >> $GITHUB_ENV
          done


      - name: Set up Git config and fetch latest
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Skyepulse"
          git config user.email "elmrys@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: Replace placeholder in README
        run: | 
          sed "s/{{TIMESTAMP1}}/$TIMESTAMP1/g; s/{{TIMESTAMP2}}/$TIMESTAMP2/g; s/{{TIMESTAMP3}}/$TIMESTAMP3/g; s/{{TIMESTAMP4}}/$TIMESTAMP4/g; s/{{TIMESTAMP5}}/$TIMESTAMP5/g; s/{{TIMESTAMP6}}/$TIMESTAMP6/g; s/{{TIMESTAMP7}}/$TIMESTAMP7/g; s/{{TIMESTAMP8}}/$TIMESTAMP8/g" README.template.md > README.md

      - name: Print variables
        run: |
          echo "TIMESTAMP = $TIMESTAMP"
          cat README.template.md
          cat README.md
    
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git status
          git add .
          git status
          git commit -m "Update README timestamp" || echo "No changes to commit"
          git push origin main
