name: Update README Timestamp

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Replace placeholder in README
        run: |
          sed "s/{{TIMESTAMP}}/${TIMESTAMP}/g" README.template.md > README.md

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Skyepulse"
          git config user.email "elmrys@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git pull origin main
          git add README.md
          git diff --quiet || git commit -m "Update README timestamp"
          git push origin main
